xpath_locator_1: str = ".//a[@href='/']"
xpath_locator_2: str = ".//button[@appscrollto='aboutSection']"
xpath_locator_3: str = ".//button[@appscrollto='contactsSection']"
xpath_locator_4: str = ".//button[contains(@class, 'header-link-guest')]"
xpath_locator_5: str = ".//button[contains(@class, 'header_signin')]"
xpath_locator_6: str = ".//header[@class='header bg-basic-dark']"
xpath_locator_7: str = ".//div[@class='header_right d-flex align-items-center']"
xpath_locator_8: str = ".//section[@class='section hero'] "
xpath_locator_9: str = ".//div[@id='aboutSection']"
xpath_locator_10: str = ".//h2[text()='Contacts']"
xpath_locator_11: str = ".//a[contains(@href, 'facebook.com') and @class='socials_link']"
xpath_locator_12: str = ".//a[contains(@href, 't.me') and @class='socials_link']"
xpath_locator_13: str = ".//a[contains(@href, 'youtube.com') and @class='socials_link']"
xpath_locator_14: str = ".//a[contains(@href, 'instagram.com') and @class='socials_link']"
xpath_locator_15: str = ".//a[contains(@href, 'linkedin.com') and @class='socials_link']"
xpath_locator_16: str = ".//div[@class='contacts_socials socials']"
xpath_locator_17: str = ".//a[contains(@class, 'contacts_link') and contains(text(), 'ithille.ua')]"
xpath_locator_18: str = ".//div[@class='container']"
xpath_locator_19: str = ".//div[@class='row']"
xpath_locator_20: str = ".//a[@class='footer_logo']"
xpath_locator_21: str = ".//span[@class='socials_icon icon icon-facebook']"
xpath_locator_22: str = ".//span[@class='socials_icon icon icon-youtube']"
xpath_locator_23: str = ".//span[@class='socials_icon icon icon-telegram']"
xpath_locator_24: str = ".//span[@class='socials_icon icon icon-instagram']"
xpath_locator_25: str = ".//span[@class='socials_icon icon icon-linkedin']"
